import test from 'node:test';
import assert from 'node:assert/strict';

import {
  parseHeaderMap,
  fingerprint,
  fingerprintRaw,
} from '../public/js/waf-core.js';

test('parseHeaderMap lower-cases and joins duplicate Set-Cookie', () => {
  const m = parseHeaderMap('Set-Cookie: a=1\nSet-Cookie: b=2\nServer: nginx');
  assert.equal(m['server'], 'nginx');
  assert.equal(m['set-cookie'], 'a=1; b=2');
});

test('detects Cloudflare from cf-ray', () => {
  const hits = fingerprint(parseHeaderMap('Server: cloudflare\ncf-ray: 7a1b2c3d'));
  assert.ok(hits.includes('Cloudflare'));
});

test('detects Imperva from x-iinfo / incap cookies', () => {
  const hits = fingerprint(parseHeaderMap('x-iinfo: 1-2-3\nSet-Cookie: visid_incap_123=abc'));
  assert.ok(hits.includes('Imperva / Incapsula'));
});

test('detects AWS CloudFront from x-amz-cf-id', () => {
  const hits = fingerprint(parseHeaderMap('Server: CloudFront\nx-amz-cf-id: abc'));
  assert.ok(hits.includes('AWS (CloudFront/ALB/WAF)'));
});

test('detects F5 BIG-IP from BIGipServer cookie', () => {
  const hits = fingerprint(parseHeaderMap('Set-Cookie: BIGipServerpool=12345'));
  assert.ok(hits.includes('F5 BIG-IP ASM'));
});

test('detects ModSecurity from a body signature', () => {
  const hits = fingerprint({}, 'This error was generated by Mod_Security');
  assert.ok(hits.includes('ModSecurity'));
});

test('plain nginx with no WAF reports just the server', () => {
  const hits = fingerprint(parseHeaderMap('Server: nginx/1.25'));
  assert.deepEqual(hits, ['Nginx']);
});

test('fingerprintRaw parses then matches', () => {
  const hits = fingerprintRaw('Server: cloudflare\ncf-cache-status: HIT', '');
  assert.ok(hits.includes('Cloudflare'));
});

test('no signatures yields an empty array', () => {
  assert.deepEqual(fingerprint({}, ''), []);
});
